CODEOWNERS
Add server directory to house backend work
Add CODEOWNER entry for server
This PR will also test the build, preview, and deployment of ephemeral instances on netlify
=> Add server directory

client/.eslintrc.json
=> remove react prop-type rule

.gitignore, .sample-env, README.md, client/README.md, docker-compose.yml
- Add docker-compose instructions to pull and spin up postgres db
- db, readme
- No server connection to DB set up
=> chore: add docker-compose for postgres db, update readme with prereqs

.editorconfig
- add editor config to sync file spacing across devs
- configs
=> chore: add editor config

.github/workflows/pylint.yml
- Create .github/workflows/pylint.yml
- Fixes #53 
- ci
-
=> chore: add black ci to PRs

scraper/Dockerfile, scraper/main.py
- To set up initial directory for the scraper
- folder structure: adds directory specifically for the scraper
- Actual functionality of the scraper: this PR only creates the directory, respective Dockerfile, and defines the entry point for the scraper
=> (chore): add initial setup for scraper

client/src/components/Filter.jsx
- a fix for the filter component (replaced foreach with find)
-
-
=> fix: Replaced ForEach in Filter

server/tests/conftest.py, server/tests/functional/test_jobs.py, server/tests/functional/test_login.py, server/tests/functional/test_signup.py, server/tests/unit/test_models.py, server/webserver/__init__.py, server/webserver/blueprints/jobs.py, server/webserver/models.py, server/webserver/queries.py
- Add initial functionality for `/jobs` route, the main route for retrieving jobs from the database
fixes #66 
- API
- keyword searching
- (to discuss) possibly creating multiple resources with one POST request. Currently one request per job.
=> (feat): add functionality for /jobs route

client/src/pages/HomePage.jsx
Fixes #110 
- Fix issue with app content on wider viewports
-
-
=> Fix app content on wider viewports

README.md, docker-compose.yml, server/Dockerfile, server/README.md, server/webserver/__init__.py, server/webserver/mock_schema.sql, server/webserver/models.py, server/webserver/queries.py
- Set up Docker for webserver along with some mock data
- fixes #115 
- Webserver Directory
-
=> Set up Docker For Server

client/src/components/InternshipCard.jsx, client/src/components/SearchResults.jsx, client/src/pages/SearchResultsPage.jsx, client/src/theme.js
Resolves #109 
- added the white container as the card wrapper in internship component
-
-
=> Card wrapper for Internship component

client/package-lock.json, client/package.json, client/src/index.jsx, client/src/utils/api.js, client/src/utils/constants.js
- Add axios function for making requests to server
fixes #108 
- Client utilities
-
=> add client function for making request to /jobs endpoint

scraper/Dockerfile, server/Dockerfile
- fixes #139 
- Change Docker base image to bullseye from alpine since alpine python image does not ship with some tools that are required to build all of the dependencies
- Server/Scraper
-
=> Change Docker images to build from bullseye

scraper/scraper.py, server/webserver/models.py
- Updates the jobs model for the database. 
- Ticket #150 
- This changes the database jobs model, such that any future jobs that are created should be done with the according data. 
- Next steps would be to take the data from the web scraper and put it in the database according to this model.
- Queries are not updated to match the new data model, and a ticket should be made for this.
=> New model for storing jobs. Ticket #150

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/components/AuthComponent.jsx, client/src/components/ErrorMessage.jsx, client/src/components/Navbar.jsx, client/src/contexts/AuthContext.jsx, client/src/pages/SignInPage.jsx, client/src/theme.js, package.json
handles #86 
- to create a Login Page
- none
- creating a user object / the authentication functionality (this will be a separate ticket)
- email/password verification
- functionality regarding signing up with google/linkedIn
- links for "Forgot Password" and "Sign Up Here"
=> feat: Sign In Page

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/pages/TestPage.jsx, client/src/utils/firebaseConfig.js
fixes #102 
- Implementing Google authentication using Firebase
- 
-
=> feat: Google Auth

.editorconfig, client/src/components/InternshipCard.jsx, client/src/components/InternshipTag.jsx, client/src/components/PostedOn.jsx, client/src/components/SearchResults.jsx, client/src/pages/SearchResultsPage.jsx
handles #25 
- added components #56 #57 #58 #59 to the internship post card components to form a complete internship post
- added some mock data for now
- mock data for the internships is in a specific JSON structure for now => will need to change once backend is established
- some little issues from tickets #56 #57 #58 #59 will need to be revisited in a later ticket
- icons for the tags not handled since this will depend on the actual filters we will be using in the future
=> feat: Create Internship Post Card

client/src/App.jsx, client/src/components/IconTextField.jsx, client/src/components/InternshipCard.jsx, client/src/components/Navbar.jsx, client/src/components/SearchBar.jsx, client/src/components/SearchButton.jsx, client/src/pages/TrackerPage.jsx
Handles #164 
- add title and search bar to the tracker page
- added a new page for tracker page
-
=> feat: Tracker page title and search bar

client/src/components/SignOutButton.jsx, client/src/pages/TestPage.jsx, client/src/theme.js
- implement the modal when sign out button is clicked and apply sign out functionality
- a new component SignOutButton.jsx is created
- currently, it is on the Test Page, so it needs to be put on the accounts page later
=> feat: Sign Out Functionality

client/src/components/TrackerColumn.jsx, client/src/pages/TrackerPage.jsx
- added scrollable columns for each category on the tracker page
- 
-
=> feat: Columns for tracker page

.github/workflows/lintchecks.yml, client/.eslintrc.json
- fix the lintchecks github action workflow since it uses a deprecated flag
- github actions
-
=> fix: Lint Check

.github/workflows/frontendtests.yml, .github/workflows/lintchecks.yml
=> fix: added manual workflow

client/src/App.jsx, client/src/components/AuthComponent.jsx, client/src/components/HiddenTextComponent.jsx, client/src/components/Navbar.jsx, client/src/components/SignInButton.jsx, client/src/components/SignUpButton.jsx, client/src/components/SocialSignUp.jsx, client/src/pages/SignInPage.jsx, client/src/pages/SignUpPage.jsx, client/src/theme.js
handles #85 
- added a Sign Up page
- None
- adding user to database (backend)
=> feat: Sign Up Page

client/src/components/StrictModeDroppable.jsx, client/src/components/TrackerCard.jsx, client/src/components/TrackerDrawer.jsx, client/src/pages/TrackerPage.jsx, client/src/utils/api.js, client/src/utils/mockData.js
- added notes feature to tracker page (for each internship tracked)
-
-
=> feat: Notes on Tracker Drawer

client/src/App.jsx, client/src/components/AuthComponent.jsx, client/src/components/CloseAccountButton.jsx, client/src/components/ConfirmActionModal.jsx, client/src/components/ErrorMessage.jsx, client/src/components/Navbar.jsx, client/src/components/SignInButton.jsx, client/src/components/SignUpButton.jsx, client/src/pages/AboutPage.jsx, client/src/pages/AccountSettingsPage.jsx, client/src/pages/BasePage.jsx, client/src/pages/SearchResultsPage.jsx, client/src/utils/api.js, client/src/utils/helper.js, client/src/utils/mockData.js
- Add the account settings page
- Add functionality for signing out, updating user account info, and closing account
-
-
=> feat: Account Settings Page

client/src/components/StatusDropdown.jsx, client/src/components/TrackerDrawer.jsx, client/src/pages/TrackerPage.jsx, client/src/utils/helper.js
Closes https://github.com/BobaTalks/internship-tracker/issues/81
- added job posting hyperlink button that opens the job posting in a new tab
- created StatusDropdown component that allows users to update the status of their tracked internship application
https://github.com/user-attachments/assets/217b6c68-8cd4-4d5d-8a95-19a138f05990
-
-
=> feat: Job Posting Hyperlink and Status Updater

client/src/components/CloseAccountButton.jsx, client/src/components/ConfirmActionModal.jsx, client/src/components/SignOutButton.jsx, client/src/components/TrackerDrawer.jsx
Closes https://github.com/BobaTalks/internship-tracker/issues/178
- Added a delete button on the tracker drawer that allows users to remove that tracked internship from their tracker
- Currently implemented as a removal from the array stored in TrackerContext, but to be replaced by API call once backend is completed
- Added `ConfirmActionModal` to confirm deletion
- Is there a better way to delete the internship without the backend?
- Is it confusing that some features are "mocked" with context, while others aren't?
https://github.com/user-attachments/assets/cbe98824-d36a-440d-bc11-cf63c8f94e17
=> feat: Delete button on tracker drawer

client/src/components/Filter.jsx, client/src/components/FiltersBar.jsx, client/src/pages/SearchResultsPage.jsx, client/src/utils/filter.js
Deals with issue #144 
Adds the number of jobs that apply to each filter option in the filter menu, as shown in the image below:
There are minimal changes to any other parts of the application besides the Filter and FilterBar components. Created a new helper function that mutates the current filter data by checking one given filter key to true. 
N/A
=> feat: Display number of matching items for each filter item
